package receipt

import (
	"bytes"
	"testing"
	"time"
)

func TestFormatRupiah(t *testing.T) {
	cases := []struct {
		input int64
		want  string
	}{
		{0, "Rp 0"},
		{500, "Rp 500"},
		{1000, "Rp 1.000"},
		{25000, "Rp 25.000"},
		{150000, "Rp 150.000"},
		{1000000, "Rp 1.000.000"},
	}
	for _, tc := range cases {
		got := FormatRupiah(tc.input)
		if got != tc.want {
			t.Errorf("FormatRupiah(%d) = %q, want %q", tc.input, got, tc.want)
		}
	}
}

func TestGenerateReceiptPDF(t *testing.T) {
	data := ReceiptData{
		OrderNumber:     "BWX-20261003-0004",
		CustomerName:    "Yoga",
		CustomerPhone:   "+6281234567890",
		OrderDate:       time.Date(2026, 10, 3, 23, 5, 0, 0, time.UTC),
		FulfillmentType: "Takeaway (Pickup)",
		Status:          "PREPARING",
		TotalAmount:     45000,
		Items: []ReceiptItem{
			{
				Name:            "Cut Pizza All In One",
				Quantity:        1,
				UnitPriceAmount: 45000,
				LineTotalAmount: 45000,
				Modifiers:       []string{"Coklat", "Keju"},
			},
		},
		PublicTrackingToken: "trk_838d05b9e00b4d0eb5110e37ab31b125f280d085",
	}

	pdfBytes, err := GenerateReceiptPDF(data)
	if err != nil {
		t.Fatalf("unexpected error generating receipt PDF: %v", err)
	}

	if len(pdfBytes) < 500 {
		t.Fatalf("expected PDF size >= 500 bytes, got %d", len(pdfBytes))
	}

	// Verify standard PDF header (%PDF-)
	if !bytes.HasPrefix(pdfBytes, []byte("%PDF-")) {
		t.Fatalf("generated bytes do not start with %%PDF- header")
	}
}

func TestGenerateReceiptPDF_WithDiscount(t *testing.T) {
	data := ReceiptData{
		OrderNumber:     "BWX-20261003-0005",
		CustomerName:    "Budi",
		CustomerPhone:   "+6281234567890",
		OrderDate:       time.Now(),
		FulfillmentType: "Takeaway (Pickup)",
		Status:          "COMPLETED",
		SubtotalAmount:  60000,
		DiscountAmount:  10000,
		DiscountName:    "Promo GoFood 10rb",
		TotalAmount:     50000,
		Items: []ReceiptItem{
			{
				Name:            "Martabak Daging Sapi",
				Quantity:        1,
				UnitPriceAmount: 60000,
				LineTotalAmount: 60000,
			},
		},
	}

	pdfBytes, err := GenerateReceiptPDF(data)
	if err != nil {
		t.Fatalf("unexpected error generating receipt PDF with discount: %v", err)
	}

	if !bytes.HasPrefix(pdfBytes, []byte("%PDF-")) {
		t.Fatalf("generated bytes do not start with %%PDF- header")
	}
}
